version: "3.9"

services:
  onboarding-api:
    build: .
    container_name: onboarding-api
    restart: always
    ports:
      - "8443:8000"
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --ssl-keyfile /etc/letsencrypt/live/rikkiee-onboarding.duckdns.org/privkey.pem
      --ssl-certfile /etc/letsencrypt/live/rikkiee-onboarding.duckdns.org/fullchain.pem
